providers = ['node', 'staticfile']

[phases.build]
cmds = ['npm install', 'npm run build']

[static]
# Change "dist" to "build" if you are using Create React App instead of Vite
dir = "dist" 
index = "index.html"
fallback = "index.html"